# Usa la imagen oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY app.py .

# Instala Flask
RUN pip install flask

# Expone el puerto 5000
EXPOSE 5000

# Comando para iniciar el servidor
CMD ["python", "app.py"]
